fix: Retool regex to accomodate urls with parentheses

diff --git a/scripts/generate-resources b/scripts/generate-resources
--- a/scripts/generate-resources
+++ b/scripts/generate-resources
@@ -30,20 +30,11 @@ declare -a FILES
 declare RESOURCES_FILE
 declare -a BOOK_DIRS
 
-get-book-dirs() {
-    # ignore the ./docs/deploy directory
-    IFS=$'\n' read -r -d '' -a BOOK_DIRS < <(
-        find 'docs/' -maxdepth 1 -mindepth 1 -type d  \! -name 'deploy'
-    ) || {
-        printf >&2 "[ERROR]: Failed to get book directories!\n"
-    }
-}
-
 get-files(){
     local search_dir
     local -r file_pattern="*.md"
-    [[ -n $1 ]] || {
-        printf >&2 "[ERROR]: Called 'get-links' with no arguments!\n"
+    [[ -n $1 && -d $1 ]] || {
+        printf >&2 "[ERROR]: Called 'get-links' with missing or bad arguments!\n"
         return 1
     }
     search_dir=$1
@@ -71,8 +62,8 @@ pull-links() {
         local link_hash=
 
         IFS=$'\n' read -r -d '' -a RESOURCES < <(
-            grep -i -E '\<https://' "$file" |
-                grep -v -E '(img)? ?src=|discord\.(gg|com)|user-attachments'
+            grep -iP '\bhttps?://' "$file" |
+                grep -vP '(img)? ?src=|discord\.(gg|com)|user-attachments|(\./assets)'
         )
 
         [[ -n "${RESOURCES[*]}" ]] || continue
@@ -81,30 +72,30 @@ pull-links() {
             local markdown_link=
             local link_hash=
             [[ $file =~ .*u([0-9]+).*\.md ]] && UNIT="${BASH_REMATCH[1]}"
+            [[ -n $resource ]] || printf "resource empty: %s\n" "$resource"
 
             # extract markdown link from the line
-            markdown_link="$(perl -pe 's/.*(\[.*?\]\(.*?\)).*/\1/' <<< "$resource")" 
+            markdown_link="$(perl -ne 'print $1 if m/(\[.*?\]\([^\s]+)/' <<< "$resource")" 
 
-            if [[ $markdown_link =~ .*(<.*>).* ]]; then
-                # Link is formatted as: <http://example.com>
-                markdown_link="${BASH_REMATCH[1]}"
-                (( count_reg_links++ ))
-            elif [[ $markdown_link =~ .*[^[\<\(](https://[^ \)]+).* ]]; then
-                # Link is unformatted: http://example.com
-                markdown_link="${BASH_REMATCH[1]}"
-                (( count_uf_links++ ))
-                continue
+            if  [[ -z $markdown_link ]]; then
+                markdown_link="$(perl -ne 'print $1 if m,([^<(]http[s]?://[^\s]+),' <<< "$resource")"
+                if [[ -n $markdown_link ]]; then
+                    # Link is unformatted: http://example.com
+                    (( count_uf_links++ )) && continue
+                fi
+
+                markdown_link="$(perl -ne 'print $1 if m,([<]http[s]?://[^\s]+),' <<< "$resource")"
+                if [[ -n $markdown_link ]]; then
+                    # Link is formatted as: <http://example.com>
+                    (( count_reg_links++ ))
+                fi
             else
-                # Link is formatted as: [Link](http://example.com)
+                # Link is formatted as: [Link Text](http://example.com)
                 (( count_md_links++ ))
             fi
             [[ -z $markdown_link ]] && continue
 
             # Fix duplicate problem
-            # Using grep to check for duplicates created a race condition
-            # - Add associative array containing links already added
-            #   - Bash can't parse markdown links as associative array keys
-            #   - use md5sum hashes
             link_hash=$(
                 sed -E 's/\/([>\)])?$/\1/' <<< "${markdown_link,,}" |
                     md5sum |
@@ -161,7 +152,7 @@ format-resources() {
     else
         printf >&2 "[ERROR]: No unitindex.md file in: %s\n" "$unitindex_file"
         local unit_count=
-        # Gather number of units from filenames if repo is not in 'case'
+        # Gather number of units from filenames if no unitindex file is present
         if [[ -z $unit_count && -d ${unitindex_file%/*} ]]; then 
             unit_count="$(grep -oP '(\d+)' \
                 <(find "${unitindex_file%/*}" -maxdepth 1 -mindepth 1 -type f -name '*.md') |
@@ -184,10 +175,13 @@ format-resources() {
     fi
 }
 
-get-book-dirs || {
-    printf >&2 "[ERROR]: Failed to fetch book directories!\n"
-    exit 1
-}
+IFS=$'\n' read -r -d '' -a BOOK_DIRS < <(
+    find 'docs/' -maxdepth 1 -mindepth 1 -type d  \
+        \! -name 'deploy' \
+        \! -name 'assets' \
+        \! -name 'stylesheets' \
+        \! -name 'beginners'
+)
 
 for dir in "${BOOK_DIRS[@]}"; do
     printf -- "#----------------- Files for dir: %s -----------------#\n" "$dir"
@@ -196,6 +190,7 @@ for dir in "${BOOK_DIRS[@]}"; do
         exit 1
     }
     RESOURCES_FILE="${dir}/resources.md"
+    ADDED_LINKS=()
     format-resources "$dir/unitindex.md"
     pull-links
 done
